feat: parser for RS_ViaOW.xml
backendsnakes/backend-flight-tickets-service pull request #1
Opened 2024-07-30 12:11 UTC by ApriCotBrain

2024-07-30 12:24 UTC, kaziamov requested changes

2024-07-30 12:24 UTC, kaziamov commented on app/parser.py
> +
Пройдись линтером, форматирование неверное местами

2024-07-30 12:24 UTC, kaziamov commented on app/parser.py
> +        return xml_dict
Возвращается xml_dict, а в аннотации list

2024-07-30 12:24 UTC, kaziamov commented on app/parser.py
> +                for item in flight_values:
Можно ли сделать алгоритм не таким сложным O(n*n*n)?

2024-07-30 12:24 UTC, kaziamov commented on app/parser.py
> +            flight["Pricing"]["currency"] = flight["Pricing"].pop("@currency")
Можно ли сделать код более читаемым?

2024-07-30 12:24 UTC, kaziamov commented on app/parser.py
> +async def get_shortest_flights(xml_data_path: str) -> list:
Может быть функции будут принимать результаты парсинга? (метод единой отвесттвенности)
Так можно будет парсить файл один раз и работать с результами для всех необходимых способов, а не парсить внутри каждого метода.

2024-07-30 12:24 UTC, kaziamov commented on tests/test_parser.py
Нет тестов

2024-08-09 17:33 UTC, kaziamov requested changes
В целом, у меня нет критичных замечаний к коду. Только пара моментов, которые можно отрефакторить позже. 

Но как как нет тестов, я не могу принять

2024-08-09 17:33 UTC, kaziamov commented on app/schemas.py
> +    arrival_time: str
на подумать: может стоит использовать тип данных datetime

потому что часовой пояс может быть критичным в планировании и нам все равно потом придется конвертировать, чтобы сравнить время

2024-08-09 17:33 UTC, kaziamov commented on app/parser_v2.py
> +def parse_all_flights(xml_data: str) -> list[Ticket]:
слишком большая функция, есть возможность разделить?

2024-08-13 11:31 UTC, ApriCotBrain commented on app/parser.py
> +        return xml_dict
резолвлю, т.к. будет другая версия парсера, этот кусок кода чуть позже удалю

2024-08-13 16:34 UTC, kaziamov submitted a review, later dismissed

2024-08-13 16:34 UTC, kaziamov commented on pyproject.toml
> +authors = ["Ольга Мелихова <melihova.o@yandex.ru>"]
English please ;)

2024-08-13 16:34 UTC, kaziamov commented on pyproject.toml
> +pytest = "^8.3.2"
Нужно поместить зависимости для тестирования в отдельную группу

2024-08-13 16:34 UTC, kaziamov commented on app/parser.py
> +async def get_all_tickets(xml_data: str) -> list[Ticket]:
Функция выглядит очень большой, стоит разделить (можно не сейчас, а похоже, отдельной задачей на рефакторинг)

2024-08-13 16:34 UTC, kaziamov commented on app/parser.py
> +async def parse_flights(
Еще одна большая функция

2024-08-13 16:37 UTC, kaziamov approved these changes

2024-08-14 10:40 UTC, ApriCotBrain commented on pyproject.toml
> +pytest = "^8.3.2"
done

2024-08-14 10:40 UTC, ApriCotBrain commented on app/parser.py
> +async def get_all_tickets(xml_data: str) -> list[Ticket]:
Ok. I'll think about it tomorrow:-)
А вообще я думаю, что здесь это ни к чему. Функция не такая и большая, плюс она как-раз собирает нужные значения из других функций поменьше.

2024-08-14 10:40 UTC, ApriCotBrain commented on app/parser.py
> +async def parse_flights(
как и договаривались, отвечает только за одно действие - парсит значения внутри одного тега.

2024-08-14 10:40 UTC, ApriCotBrain commented on pyproject.toml
> +authors = ["Ольга Мелихова <melihova.o@yandex.ru>"]
done:-)

2024-08-15 10:16 UTC, merged